### ISSUE TITLE
Too many tags describing this tag. Please fix it and resubmit.

### ISSUE THREAD

**Issue by kaihendry** [ikeikeikeike/go-sitemap-generator#10]
I'm using you software to generate a video sitemap, e.g.

      <video:category>action</video:category>
      <video:category>crime</video:category>

But Google search console seems to complain when there is more than one category. https://wordpress.org/support/topic/plugin-google-xml-sitemap-for-videos-invalid-xml-error-google-webmaster-tools/ has some background to the issue.

And https://developers.google.com/webmasters/videosearch/sitemaps#video-sitemap-tag-definitions spells it out, **Usually a video will belong to a single category**.

The answer is probably to use tags instead of categories.

**Comment by ikeikeikeike** [comment]
Yes, I knew that sitemap's specification.  I'm not sure yet, I'm afraid have you written in`slice type` into category element ? Because I've got correct result after I tried to write this code in following this [README](https://github.com/ikeikeikeike/go-sitemap-generator#video-sitemaps).

**Comment by kaihendry** [comment]
Oh yes, you're right.
