### ISSUE TITLE
Format sitemap XML

### ISSUE THREAD

**Issue by kaihendry** [ikeikeikeike/go-sitemap-generator#11]
I noticed by default the XML sitemap is just one long line. Therefore when diagnosing issues in <https://www.google.com/webmasters/tools> it only gives that line number as to an indicator to where my problem is:

<img src=http://s.natalian.org/2016-11-23/line_number.png>

My workaround is to use `xmlstarlet fo sitemap1.xml  > sitemap-formatted.xml` so that the line numbers a sitemap test returns are useful. So I was thinking maybe stm could just pretty print the XML to begin with?

**Comment by ikeikeikeike** [comment]
hi
You mean, it allows pretty formatting to all of output xml to begin with, by option like a sm.SetPretty(false) method ?"

**Comment by kaihendry** [comment]
Yes, exactly! So that when Google flags an issue on a line number it's easier to track down the problem.

**Comment by ikeikeikeike** [comment]
Respond by #12
