### ISSUE TITLE
Remove AWS dependency

### ISSUE THREAD

**Issue by IvanRave** [ikeikeikeike/go-sitemap-generator#3]
I don't use AWS for hosting
Why I must to download AWS libraries:
- cannot find package "github.com/aws/aws-sdk-go/aws"
- cannot find package "github.com/aws/aws-sdk-go/aws/credentials"
- cannot find package "github.com/aws/aws-sdk-go/aws/session"
- cannot find package "github.com/aws/aws-sdk-go/service/s3/s3manager"

**Comment by ikeikeikeike** [comment]
done: https://github.com/ikeikeikeike/go-sitemap-generator/commit/578329d4e9fec052873603bd2299fbf7d64db33c
